### ISSUE TITLE
/envoy/verify-params-header can cause infinite auth loop

### ISSUE THREAD

**Issue by Nessex** [travisghansen/external-auth-server#30]
Thanks for this project! It's super useful.

We got really stuck for a little while in an infinite auth loop when trying to use this from an envoy ext_authz filter (similar to your examples: [istio example](https://github.com/travisghansen/external-auth-server/blob/master/examples/istio.yaml), https://github.com/travisghansen/external-auth-server/issues/23#issuecomment-522617850 ).

The ultimate fix ended up being to set `pathPrefix` to `/envoy/verify-params-header/anythingherewillwork`. That makes it correctly match the express route: https://github.com/travisghansen/external-auth-server/blob/154218a725e716642af0607eb47597d40b1c2737/src/server.js#L425 (in fact, in hindsight even just an extra `/` on the path will work)

I'm not sure what made those previous examples work with just `/envoy/verify-params-header`, maybe something automatically appended to the paths?

I think a good change to make this easier to use, would be to update the route to just `/envoy/verify-params-header`, but I'm not sure if that's how you intended it to be used.

Here's the full filter we ended up with, in case it's useful:

```yaml
http_filters:
- name: envoy.ext_authz
config:
    failure_mode_allow: false
    http_service:
        path_prefix: /envoy/verify-params-header/anythingherewillwork
        authorization_request:
          allowed_headers:
            patterns:
            - exact: cookie
            - exact: X-Forwarded-Host
            - exact: X-Forwarded-Method
            - exact: X-Forwarded-Proto
            - exact: X-Forwarded-Uri
          headers_to_add:
          - key: "x-eas-verify-params"
            value: '{"config_token_store_id": "env_token_store", "config_token_id": "token_id_1"}'
        server_uri:
          uri: http://external-auth-server.internal-service.svc.cluster.local
          cluster: ext-authz
          timeout: 10s
        status_on_error:
          code: Forbidden
        with_request_body:
          allow_partial_message: true
          max_request_bytes: 4096
- name: envoy.router
  typed_config: {}
```

This works excellent for us with OIDC and GCP Identity Platform! 🎉

**Comment by travisghansen** [comment]
Thanks for the kind words! This is pretty interesting. I'm admittedly very weak with envoy...I basically setup istio and ambassador in less than an hour just to crudely test it out and it got it working so it's a weak code path/documentation for sure.

If there's anything you can think of that would cause the discrepancy let me know. In the mean time, are you saying this works `/envoy/verify-params-header/` and this does not `/envoy/verify-params-header`?

I have this on my ambassador service/mapping definition for example: `prefix: /`...I wonder if that makes any difference.

**Comment by travisghansen** [comment]
If I understand your comment correctly too we can't really alter the wildcard route. The way envoy handles external auth is it requests literally the same URL so it could be anything however many 'directories' deep too.

ie: original request to `/foo/bar/baz` gets sent to the auth service as (with prefix added of course in this example) `/envoy/verify-params-header/foo/bar/baz`

**Comment by Nessex** [comment]
> are you saying this works /envoy/verify-params-header/ and this does not /envoy/verify-params-header?

Exactly

> The way envoy handles external auth is it requests literally the same URL so it could be anything however many 'directories' deep too.

Hmm, I don't have access to my installation at the moment, but I'm keen to test any route that's got more of a path now. I think all my requests to test auth started with just `https://website.tld`, nothing else in the path.

In other words, I had a setup like:
```
envoy: https://website.tld 
├─── /(oauth|envoy)/* -> https://external-auth-server.internal
├─── /service-1/*     -> https://service-1.internal
└─── *                -> https://service-2.internal
```
 I tried to make a request to `https://website.tld`, which got me stuck in an auth loop.

I didn't try going to `https://website.tld/hello` or `https://website.tld/service-1/hello` to trigger the auth flow, maybe those would have worked?

In the `https://website.tld` case, envoy does the auth request to `https://external-auth-server.internal/envoy/verify-params-header`
In the `https://website.tld/hello` case, envoy _might_ instead hit `https://external-auth-server.internal/envoy/verify-params-header/hello`

The former does not match the express route, but the latter does. If that's true (I can check all this on Monday), the fix might be as simple as: 

```javascript
app.all("/envoy/verify-params-header(/*)?", async (req, res) => { 
```

**Comment by travisghansen** [comment]
Ahhh, now that makes more sense. Probably need 2 routes defined, the wildcard and just the endpoint itself. I'll add it to the next release (messing with another project ATM so it'll be a week or two probably).

With your config that retains the trailing / in the prefix can you confirm routes which have a path still work?

Thanks!

**Comment by travisghansen** [comment]
It looks like your suggested route definition should work. If you're in a position to test it out let me know.

**Comment by Nessex** [comment]
Thank you! With the config pasted at the top (using `path_prefix: /envoy/verify-params-header/`) I'm still able to auth just fine even if I make a request to `https://website.tld/hello` when not logged in.

Presumably envoy is making an auth request to `https://external-auth-server.internal/envoy/verify-params-header//hello`, and that's valid enough :)

Will get back to you about the route suggestion on Monday when I can redeploy!

**Comment by travisghansen** [comment]
Ok cool. Thanks again for the info and report!

**Comment by travisghansen** [comment]
Which version of istio are you running? I can't seem to reproduce this issue...the request comes through for me with a trailing slash (to the auth service) even when hitting an end-service endpoint without the trailing slash.  All of this with `pathPrefix: /envoy/verify-params-header`

**Comment by travisghansen** [comment]
I've released new images which should resolve this. `latest` and `v0.5.5`.

**Comment by Nessex** [comment]
Apologies for the delay, I've tested that new image and strangely enough it has the original issue still. It does break the hack I used (`path_prefix: /envoy/verify-params-header/`) though. I suspect that while the path is related to the problem, I was probably wrong about it being because of the mismatch with express routes.

In further testing I found what you said, which is that EAS-side you get `/envoy/verify-params-header/` as `req.url` even for requests just to `https://website.tld`. With the hack, my auth requests were indeed going to `/envoy/verify-params-header//`.

I don't expect I'll get any more time to look at this this week, but leave it with me and I'll try to come up with an answer or at least a more complete way to replicate the issue on your side. As for istio, we're not actually using Istio here, just a plain envoy deployment. Specifically, I've been using the `envoyproxy/envoy:v1.11.1` image with the config above.

**Comment by travisghansen** [comment]
Interesting. Let me know what you find out...I could not reproduce the behavior you saw so I'm interested to know what's actually going on here..

**Comment by mlushpenko** [comment]
Interestingly, we experienced the same and also added hack with extra `/` at the end of `path_prefix`. When you will do next release for this https://github.com/travisghansen/external-auth-server/issues/29, I will check again which version we are using and if the hack is still needed.

**Comment by travisghansen** [comment]
Is it possibly related to recursion on the service? Meaning, requests to eas are trying to be auth'd by eas (itself)? Somehow the different url is altering the behavior?

**Comment by mlushpenko** [comment]
We do still use it for now:

```
{"service":"external-auth-server","level":"silly","message":"verify request details: {\"url\":\"/envoy/verify-params-header//\",\"params\":{\"0\":\"/\"},\"query\":{},}
```

I'd think that's not the case about recursion. Remember you said that eas shouldn't be protected by authentication? With that in mind, I wouldn't think that requests to eas are trying to be auth'd by eas.

**Comment by travisghansen** [comment]
They shouldn't be correct, but particularly with something like envoy which applies much more broadly than specific settings on an ingress it could be an issue.

I don't suspect it's the issue since it seems pretty unlikely that the rules would be getting applied on a path basis vs at the service level..mostly just throwing out ideas at this point.

**Comment by mlushpenko** [comment]
@travisghansen we tested your new release - still doesn't work without extra `/` but does work with it, so it didn't break the hack for us. Any logs or service setup that may be helpful?

**Comment by travisghansen** [comment]
Yeah, scale down to 1 replica set log level to `silly` and put it in a loop and send over a few loops worth of logs. Make sure to strip any sensitive data (and/or email it to me directly).

Thanks!

**Comment by travisghansen** [comment]
Did either of you end up getting to the bottom of this? I'll have a little time to get back to cleaning up a few things with this project this week.

**Comment by mlushpenko** [comment]
Nope, but I still can send you the logs if you have some time now, how can I send it to you directly?

**Comment by travisghansen** [comment]
Email on my profile would be great.

**Comment by mlushpenko** [comment]
I must have been blind or something - was sure I checked your profile before posting the question :) ANyway, sent you logs with good and bad responses.

**Comment by travisghansen** [comment]
Great thanks! I'll review and see if I can find anything.

**Comment by travisghansen** [comment]
I see what I believe is the issue but I'm not entirely sure why it's hitting the issue. I'm seeing in the output `x-forwarded-uri: "/"` when hitting the `/envoy/verify-params-header/` endpoint. I've tested as best I can with the log data I was sent and it appears it should *never* get set to simply `/`. The only thing I can think of at this point is if istio/envoy is selectively setting that value in certain scenario and not in others...seems odd.

The setting of that value happens conditionally in the handler as such:

```
if (!req.headers["x-forwarded-uri"]) {
    req.headers[
      "x-forwarded-uri"
    ] = externalAuthServer.utils.get_envoy_forwarded_uri(req, 3);
  }
```

I'm interested to know if you can make your own build with the condition removed? Or before the condition add some logging of the request before it gets altered?

**Comment by travisghansen** [comment]
I went ahead and removed the conditional in `next` branch. Try it out and let me know what you get this time. I can't think of any situation where we'd not want the correct value based on envoy behavior/spec even if it's been set erroneously/incompletely upstream.

The conditional may not be the issue at all but we'll try it out and see what we get.

**Comment by travisghansen** [comment]
Just released `v0.6.0`, closing.
